[bootstrap.brew.taps]
"fairwindsops/tap" = "https://github.com/fairwindsops/homebrew-tap.git"
"puma/puma" = "https://github.com/puma/homebrew-puma.git"
"qmk/qmk" = "https://github.com/qmk/homebrew-qmk.git"
"stripe/stripe-cli" = "https://github.com/stripe/homebrew-stripe-cli.git"
"vitobotta/tap" = "https://github.com/vitobotta/homebrew-tap.git"

[bootstrap.packages]
"brew:cloudflared" = "latest"
"brew:fairwindsops/tap/nova" = "latest"
"brew:flyctl" = "latest"
"brew:helm" = "latest"
"brew:k9s" = "latest"
"brew:mas" = "latest"
"brew:minikube" = "latest"
"brew:mole" = "latest"
"brew:puma/puma/puma-dev" = "latest"
"brew:qemu" = "latest"
"brew:qmk/qmk/qmk" = "latest"
"brew:qt" = "latest"
"brew:spotify_player" = "latest"
"brew:stripe/stripe-cli/stripe" = "latest"
"brew:tailscale" = "latest"
"brew:vitobotta/tap/hetzner_k3s" = "latest"
"brew:wb32-dfu-updater_cli" = "latest"
"brew-cask:hot" = "latest"
"brew-cask:imageoptim" = "latest"
"brew-cask:launchos" = "latest"
"brew-cask:nvidia-geforce-now" = "latest"
"brew-cask:omnidisksweeper" = "latest"
"brew-cask:qmk-toolbox" = "latest"
"brew-cask:the-unarchiver" = "latest"
"brew-cask:vlc" = "latest"
"mas:1019371109" = "latest"
"mas:1470584107" = "latest"
"mas:1381004916" = "latest"
"mas:6758070650" = "latest"
"mas:1475387142" = "latest"
"mas:425424353" = "latest"

[dotfiles]
"~/.gitconfig.local" = "dotfiles/profiles/home/gitconfig"
"~/.zshrc.local" = "dotfiles/profiles/home/zshrc"
