require("nvchad.mappings")

local map = vim.keymap.set

-- Normal mode mappings
map("n", "<C-k>", function()
  vim.lsp.buf.format()
end, { desc = "Format buffer" })

map("n", "<leader>th", function()
  require("nvchad.themes").open()
end, { desc = "telescope nvchad themes" })

map("n", "Y", ":%y+ <CR>", { desc = "Yank whole file" })
map("n", "<C-t>", function()
  require("nvchad.themes").open()
end, {})
-- map("n", "<C-t>", ":%s/<C-r><C-w>//gc<Left><Left><Left>", { desc = "Replace word under cursor (confirmation)" })
map("n", "<C-r>", ":%s/<C-r><C-w>//gc<Left><Left><Left>", { desc = "Replace word under cursor with onfirmation" })
map("n", "<C-d>", "<ESC>^dd", { desc = "Delete whole line" })
map("n", "<C-/>", function()
  require("Comment.api").toggle.linewise.current()
end, { desc = "Comment line" })
map("n", "<C-n>", ":NvimTreeToggle<CR>", { desc = "Toggle tree" })
map("n", "<C-;>", ":m .-2<CR>==", { desc = "Move line up" })
map("n", "<C-s>", "<ESC> <cmd> w <CR>", { desc = "Save the file" })
map("n", "<C-h>", "<cmd>NvimTreeFocus<CR>", { desc = "Focus on the tree" })
map("n", "<C-l>", "<cmd>wincmd l<CR>", { desc = "Focus on the buffer" })
map("n", "<A-Up>", ":m .-2<CR>==", { desc = "Move line up" })
map("n", "<C-'>", ":m .+1<CR>==", { desc = "Move line down" })
map("n", "<A-Down>", ":m .+1<CR>==", { desc = "Move line down" })
map("n", "<C-o>", ":Telescope find_files <CR>", { desc = "Find all files" })
map("n", "<C-p>", ":Telescope git_files <CR>", { desc = "Find files added to Git" })
-- map("n", "<C-p>", ":Tv <CR>", { desc = "Find files added to Git" })
map("n", "<C-z>", "<cmd> undo <CR>", { desc = "Undo" })
map("n", "<leader>gs", ":Telescope git_status <CR>", { desc = "Git status" })
map("n", "<leader>gg", ":LazyGit <CR>", { desc = "LazyGit" })
map("n", "<C-f>", ":Telescope live_grep <CR>", { desc = "live grep" })
map("n", "<C-b>", "<ESC>^i", { desc = "beginning of line" })
map("n", "<A-Left>", "<ESC>^", { desc = "beginning of line" })
map("n", "<A-Right>", "<End>", { desc = "end of line" })
map("n", "<C-S-d>", "<ESC> yyp", { desc = "Duplicate line" })
map("n", "<C-e>", "<End>", { desc = "end of line" })
map("n", ":", "<cmd>FineCmdline<CR>", { desc = "CmdLine" })
map("n", "q", function()
  require("nvchad.tabufline").close_buffer()
end, { desc = "Close current buffer" })

-- Visual mode mappings
map("v", "<A-Up>", ":m '<-2<CR>gv=gv", { desc = "Move block up" })
map("v", "<A-Down>", ":m '>+1<CR>gv=gv", { desc = "Move line down" })
map("v", "<C-/>", "gc", { desc = "Comment selection" })

-- Insert mode mappings
map("i", "<C-BS>", "<C-w>", { desc = "Delete previous word" })
map("i", "<A-Up>", "<ESC> :m .-2<CR>== i", { desc = "Move line up" })
map("i", "<A-Down>", "<ESC> :m .+1<CR>== i", { desc = "Move line down" })
map("i", "<A-Left>", "<ESC>^i", { desc = "beginning of line" })
map("i", "<A-Right>", "<End>", { desc = "end of line" })
map("i", "<C-s>", "<ESC> <cmd> w <CR> i", { desc = "Save" })
map("i", "<C-z>", "<ESC> <cmd> undo <CR> i", { desc = "Undo" })
map("i", "<C-S-d>", "<ESC> yyp i", { desc = "Duplicate line" })
