export GOPATH="$HOME/go"
export ZSH="$HOME/.oh-my-zsh"
export BUN_INSTALL="$HOME/.bun"
export CDPATH="$CDPATH:$HOME/Projects"
export ZSH_COMPDUMP="$ZSH/cache/.zcompdump-$HOST"
export BULB_HOST="192.168.178.112"
export BULB_PORT="38899"
export EDITOR="cursor --wait"
export VISUAL="$EDITOR"
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/18/bin"

typeset -U path

export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.spicetify"
export PATH="$HOME/.opencode/bin:$PATH"
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/opt/zerobrew/prefix/bin:$PATH"

DISABLE_AUTO_UPDATE="true"

VSCODE='cursor'

zstyle ':omz:update' mode reminder

[ -f "$HOME/.secrets" ] && source "$HOME/.secrets"

plugins=(
  ansible
  brew
  bundler
  encode64
  genpass
  git
  macos
  mise
  rails
  terraform
  tmux
  uv
  vscode
  # This has to be in this order
  fzf-tab
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

export RAILS_EDITOR="cursor"

if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

source "$HOME/.aliases"
source "$HOME/.functions"

eval "$(atuin init zsh --disable-up-arrow)"
eval "$(starship init zsh)"

if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init zsh)"; fi

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

