#!/usr/bin/env bash

set -euo pipefail

plugins_dir="${HOME}/.oh-my-zsh/custom/plugins"

mkdir -p "$plugins_dir"

sync_plugin() {
  local repo="$1"
  local target="$2"

  if [ -d "$target/.git" ]; then
    git -C "$target" pull --ff-only
    return
  fi

  if [ -e "$target" ]; then
    return
  fi

  git clone --depth=1 "$repo" "$target"
}

sync_plugin "https://github.com/zsh-users/zsh-autosuggestions" "$plugins_dir/zsh-autosuggestions"
sync_plugin "https://github.com/marlonrichert/zsh-autocomplete.git" "$plugins_dir/zsh-autocomplete"
sync_plugin "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$plugins_dir/zsh-syntax-highlighting"
sync_plugin "https://github.com/Aloxaf/fzf-tab" "$plugins_dir/fzf-tab"
