#!/usr/bin/env bash

set -e

echo "Removing existing NvChad"
rm -rf ~/.config/nvim
echo "Removed ~/.config/nvim"
rm -rf ~/.local/state/nvim
echo "Removed ~/.local/state/nvim"
rm -rf ~/.local/share/nvim
echo "Removed ~/.local/share/nvim"

echo "Removed existing NvChad"

echo "Cloning NvChad"
git clone https://github.com/NvChad/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

echo "Done"
