#!/usr/bin/env bash

set -e

echo "Backing up old nvim config if exists"
mv ~/.config/nvim ~/.config/nvim.bak || true

echo "Cloning NvChad"
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

echo "Done"
